version: '3'

services:
  erddap:
    container_name: erddap
    image: axiom/docker-erddap:2.18
    restart: unless-stopped
    hostname: dummy-erddap
    env_file:
      - /etc/odi/odi.env
    ports:
      - ${ODI_ERDDAP_PORT}:8080
    volumes:
      - /etc/odi/volumes/erddap/conf:/usr/local/tomcat/content/erddap
      - /etc/odi/volumes/erddap/erddapData:/erddapData   # bind mount for ERDDAP internal data
      - /etc/odi/volumes/erddap/datasets:/datasets # bind mount for user data files
      - /etc/odi/volumes/erddap/custom_logo.png:/usr/local/tomcat/webapps/erddap/images/custom_logo.png