services:
#------------------------------------------------#
# SensorThings API for Time Series
#------------------------------------------------#
  sta_ts_master:
    image: enocmartinez/sta-timeseries:0.0.3
    container_name: sta_ts_master
    env_file:
      - /opt/odi/odi.env
      - sta-ts-master.env  # add minor detail in custom env file
    networks:
      - sensorthings-net
    ports:
      - ${ODI_STA_TS_MASTER_PORT}:5000

networks:
  sensorthings-net:
    external: true