version: '3'

services:
  # NGINX reverse-proxy
  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    env_file:
      - ../../secrets/network.env
    volumes:
      - ../../volumes/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../../volumes/nginx/ssl:/ssl_keys
    network_mode: host