version: '3'

services:
  # NGINX reverse-proxy
  reverse:
    container_name: reverse
    build:
      context: ./build
      dockerfile: Dockerfile
    hostname: reverse
    ports:
      - 80:80
      - 443:443
    env_file:
      - /etc/odi/odi.env
    environment:
      - CUSTOM_VAR=holahola
    volumes:
      #- /etc/odi/volumes/proxy/env_to_nginx.py:/tmp/env_to_nginx.py
      - /etc/odi/volumes/proxy/nginx.conf.template:/etc/nginx/nginx.conf.template
      #- /etc/odi/volumes/proxy/fileserver.conf.template:/etc/fileserver/fileserver.conf.template
      - /etc/odi/volumes/proxy/ssl:/ssl_keys



