services:
  # NGINX reverse-proxy2
  reverse:
    container_name: proxy
    image: nginx:stable-bullseye
    hostname: reverse
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./volumes/ssl:/ssl_keys:ro
      - ./volumes/log:/var/log/nginx
      - ./volumes/goaccess:/var/goaccess:ro

