#!/usr/bin/env python3
"""
This script sets up all the required rules for iptables in the ODI entry point (the VM running the fileserver reverse proxy)

author: Enoc Martínez
institution: Universitat Politècnica de Catalunya (UPC)
email: enoc.martinez@upc.edu
license: MIT
created: 3/11/23
"""
import yaml
import rich
import os
from argparse import ArgumentParser
import docker
import subprocess
try:
    from .utils import process_infrastructure_file, print_infrastructure_conf, run_subprocess
except ImportError:
    from utils import process_infrastructure_file, print_infrastructure_conf, run_subprocess


def start_service(service):
    if not os.path.isdir(service):
        rich.print(f"[red]ERROR: folder '{service}' does not exist!")
        exit(1)

    os.chdir(service)
    rich.print(f"Starting service '{service}'...")
    rich.print("docker compose up -d")
    os.chdir("..")

def create_docker_network(name):
    """
    Checks if a network exists in docker and creates it
    :param name: network name
    :return:
    """
    client = docker.from_env()
    nets = client.networks.list(filters={"name": name})
    if len(nets) == 0:
        # rich.print(f"Creating network '{name}'")
        client.networks.create(name=name)
    # else:
    #     rich.print(f"Network '{name}' already exists, skipping")

def create_odi_env_file(path: str, services: dict):
    """
    Creates an env file with the services
    :param services:
    :return:
    """

    assert(os.path.exists(path) == True)
    assert (type(services) == dict)

    lines = [
        f"#!/bin/bash\n",
        f"# ============================================ #\n",
        f"#     Open Data Infrastructure config file     #\n",
        f"# ============================================ #\n",
        f"# This file has been autogenerated from setup_network.py, please do not edit",
        f"\n\n",
        f"\n"
    ]
    for name, address in services.items():
        host, port = address.split(":")
        ip = conf["addresses"][host]
        name = name.upper()
        lines.append("\n")
        lines.append(f"# Network config for ODI service {name}\n")
        lines.append(f"export ODI_{name}_IP=\"{ip}\"\n")
        lines.append(f"export ODI_{name}_PORT={port}\n")

    lines.append("\n")
    lines.append("# List of variables that need to be passed to processed by envsubst at fileserver setup\n")


    odi_env_file=os.path.join(path, "odi.env")
    with open(odi_env_file, "w") as f:
        f.writelines(lines)

def create_port_mapping(conf):
    """
    Creates port mapping in the machine
    """

    # Check that all
    for m in conf["port_mappings"]:
        os.chdir(os.path.join(conf["path"], "odi","scripts"))
        script = "./add_nat_rule.sh"
        cmd = f'sudo {script} {m["src_port"]} {m["dst_ip"]} {m["dst_port"]} {m["protocol"]}'
        # Run script as a subprocess
        run_subprocess(cmd, allow_fail=True)


if __name__ == "__main__":
    argparser = ArgumentParser()
    argparser.add_argument("-i", "--infrastructure", help="Path no infrastructure.yaml", type=str, default="/etc/odi/infrastructure.yaml")
    argparser.add_argument("-f", "--force", action="store_true", help="If set, the script will skip the proxy machine check")
    argparser.add_argument("-v", "--verbose", action="store_true", help="shows verbose output", default=False)
    argparser.add_argument("-s", "--script", type=str, help="path to add_nat_rule.sh script", default="./add_nat_rule.sh")
    args = argparser.parse_args()

    if not os.path.exists(args.infrastructure):
        rich.print(f"[red]ERROR: Infrastructure file does not exist (path {args.infrastructure})\n")
        exit(1)

    if not os.path.isfile(args.script):
        rich.print(f"[red]ERROR: add_nat_rule.sh not found (path {args.script})\n")
        exit(1)


    rich.print("[cyan]# ======================================= # ")
    rich.print("[cyan]# Open Data Infrastructure network setup  # ")
    rich.print("[cyan]# ======================================= # ")
    rich.print(f"Opening infrastructure file {args.infrastructure}")

    with open(args.infrastructure) as f:
        infrastructure = yaml.safe_load(f)["infrastructure"]

    rich.print(f"Loading infrastructure.yaml...", end=False)
    conf = process_infrastructure_file(infrastructure)
    if args.verbose:
        print_infrastructure_conf(conf)
    rich.print("[green]ok")

    hostname = os.uname().nodename
    rich.print(f"Detecting hostname...[green]{hostname}")

    rich.print("Creating docker networks...", end="")
    for network_name, network_host in conf["docker_networks"].items():
        if hostname == network_host:
            create_docker_network(network_name)
    rich.print(f"[green]ok")

    # Create the network env file
    rich.print(f"Creating odi.env file...", end="")
    create_odi_env_file(conf ["path"], conf["services"])
    rich.print("[green]ok")

    rich.print("Setting up port mappings via iptables...", end="")
    if hostname == infrastructure["entry_point"]:
        create_port_mapping(conf)
        rich.print("[green]ok")
    else:
        rich.print("[yellow]skipped")

    rich.print("\n[green]ODI network setup complete!")

    rich.print("To load new configuration run $ source /etc/environment")
