version: '3.9'

services:

  #------------------------------------------------#
  # SensorThings Database from TimscaleDB HA image
  #------------------------------------------------#
  sta_db:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: postgres_postgis_timescaledb:local
    container_name: sta_db
    env_file:
      - /etc/odi/secrets/sensorthings.env
      - /etc/odi/odi.env
    ports:
      - "5432:5432"
    networks:
      - sensorthings-net
    volumes:
      - /etc/odi/volumes/sensorthings/pgdata:/home/postgres/pgdata/data
      - /tmp/sta_db_copy/data:/tmp/sta_db_copy/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "sensorthings" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 10s


  #------------------------------------------------#
# FROST-Server
#------------------------------------------------#
  sta:
    image: fraunhoferiosb/frost-server:latest
    container_name: sensorthings
    depends_on:
      - sta_db
    networks:
      - sensorthings-net
    env_file:
      - /etc/odi/secrets/sensorthings.env
      - /etc/odi//odi.env
    environment:
      - maxTop=100000
      - http_cors_enable=true
      - http_cors_allowed.origins=*
      - persistence_db_driver=org.postgresql.Driver
      - persistence_autoUpdateDatabase=true
      - maxDataSize=50000000 # default is 25 MB, upgraded to 50
      - enableMultiDatastream=false
      - enableActuation=false
      - bus_workerPoolSize=50  ## max 50 threads
      - bus_queueSize=10000000  # 10 MB (default is unknown)
      - mqtt_Enabled=false
    ports:
      - ${ODI_SENSORTHINGS_PORT}:8080

  #------------------------------------------------#
  # SensorThings TimeSeries
  #------------------------------------------------#
  sta-timeseries:
    image: enocmartinez/sensorthings-timeseries:v0.2.1-ubuntu
    container_name: sta-timeseries
    depends_on:
      - sta
    networks:
      - sensorthings-net
    env_file:
      - /etc/odi/secrets/sensorthings.env
    ports:
      - ${ODI_SENSORTHINGS_TS_PORT}:3000
    healthcheck:
      test: curl --fail http://localhost:3000/Sensors || exit 1
      interval: 60s
      retries: 1
      timeout: 2s
    restart: unless-stopped


networks:
  sensorthings-net:
    external: true